# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Deploy:
    environment: primary
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Install NodeJS
      - name: Install NodeJS
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '16'
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install VSCE
        run: npm install -g vsce
        
      - name: Install Webpack Dependencies
        run: npm install -g esbuild webpack webpack-cli

      - name: Package Extension
        run: vsce package -o extension.vsix
        
      - name: Find Version
        id: find-version
        run: |
          ver=$(npm pkg get version)
          ver=${ver//\"/}
      
      - name: Publish to DevOps
        run: vsce publish
        env:
          VSCE_PAT: ${{ SECRETS.DEPLOYTOKEN }}
      
      - name: Publish GitHub Release
        run: |
          echo ${{ github.token }} | gh auth login --with-token
          gh release create $ver extension.vsix -F CHANGELOG.md -d
      
