name: Preview
on:
  workflow_dispatch:
jobs:
  Preview:
    environment: preview
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Install NodeJS
      - name: Install NodeJS
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '16'
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install VSCE
        run: npm install -g vsce
        
      - name: Install Webpack Dependencies
        run: npm install -g esbuild webpack webpack-cli

      - name: Package Extension
        run: vsce package -o extension.vsix
      
      - name: Publish to DevOps
        run: vsce publish --pre-release
        env:
          VSCE_PAT: ${{ SECRETS.DEPLOYTOKEN }}
      
      - name: Publish GitHub Release
        run: |
          ver=$(npm pkg get version)
          ver=${ver//\"/}
          reg="^(#{1,2}\s$ver(?:\n.+)+)"
          grep -zoP $reg CHANGELOG.md > notes.md
          tr < notes.md -d '\000' > release-notes.md
          echo ${{ github.token }} | gh auth login --with-token
          echo gh release create $ver extension.vsix -F release-notes.md -d
          gh release create $ver extension.vsix -F release-notes.md -p
